### ISSUE TITLE
db leak

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/vityBot#16]
https://github.com/GDGVIT/vityBot/blob/master/modules/factoid/modules/attendance/misc/makeDB.py#L14

**Comment by shubham0704** [comment]
There are 2 commits older commits also which show the leak. Will remove it asap.

**Comment by SuryaThiru** [comment]
Besides we are cloning it to a new DB

**Comment by SuryaThiru** [comment]
we have moved to a new DB
